### ISSUE TITLE
Change ports in vis.py 

### ISSUE THREAD

**Issue by nieiwona** [JPoziemski/ADP_project#62]
Change localhost to '0.0.0.0' (4 places) and add host='0.0.0.0' in app.run() as below:

def index():
    """ Generate a script to load the session and use the script in the rendered page. """
    script = server_document('http://0.0.0.0:5001/bkapp')
    return render_template("index.html", script = script)

def bk_worker():
    """ Run Bokeh server. """
    server = Server(
        {'/bkapp': bokeh_app},
        io_loop = IOLoop(),
        allow_websocket_origin = ["0.0.0.0:{}".format(port)], port = port
    )
    server.start()
    server.io_loop.start()

from threading import Thread
Thread(target = bk_worker).start()

if __name__ == '__main__':
    print('Opening single process Flask app with embedded Bokeh application on http://0.0.0.0:{}/'.format(port))
    webbrowser.open_new("http://0.0.0.0:{}/".format(port))
    app.run(port = port, debug = False, host='0.0.0.0')

**Comment by szymczakpau** [comment]
Fixed
